services:
  frontend:
    build:
      context: ./
    container_name: portfolio
    expose:
      - 4321
    ports:
      - "81:4321"
    #networks:
    #  - proxy
#networks:
#  proxy:
#    external: true